Repository tofugu/wanikani-knowledge-guide, pull requests merged in 2018-12, with the labels that each got.

#6 Posts — Design Fixes 20181211
  Gemfile
  Gemfile.lock
  _layouts/default.html
  _layouts/post.html
  _posts/2018-10-31-first-lessons.md
  _posts/2018-10-31-first-reviews.md
  _posts/2018-10-31-how-wanikani-works.md
  _posts/2018-10-31-leveling-up.md
  _posts/2018-10-31-unlocking-kanji.md
  _posts/2018-10-31-unlocking-vocabulary.md
  _posts/2018-10-31-waiting-for-reviews.md
  _posts/2018-10-31-wanikani-free.md
  _posts/2018-10-31-wanikani-premium-membership.md
  _posts/2018-11-25-android-app.md
  _posts/2018-11-25-browser-support.md
  _posts/2018-11-25-can-i-skip.md
  _posts/2018-11-25-card-declined.md
  _posts/2018-11-25-common-mistakes.md
  _posts/2018-11-25-double-n.md
  _posts/2018-11-25-furigana.md
  _posts/2018-11-25-how-do-i-type.md
  _posts/2018-11-25-iOS-app.md
  _posts/2018-11-25-kanji-audio.md
  _posts/2018-11-25-language-options.md
  _posts/2018-11-25-learning-method.md
  _posts/2018-11-25-numerals.md
  _posts/2018-11-25-offline-mode.md
  _posts/2018-11-25-onyomi-kunyomi.md
  _posts/2018-11-25-payment-methods.md
  _posts/2018-11-25-premium-content.md
  _posts/2018-11-25-prereqs.md
  _posts/2018-11-25-radical-names.md
  _posts/2018-11-25-radicals-kanji-vocab.md
  _posts/2018-11-25-readings-vs-meanings.md
  _posts/2018-11-25-refunds.md
  _posts/2018-11-25-reporting-errors.md
  _posts/2018-11-25-reset-level.md
  _posts/2018-11-25-reset-reviews.md
  _posts/2018-11-25-small_characters.md
  _posts/2018-11-25-srs.md
  _posts/2018-11-25-stroke-order.md
  _posts/2018-11-25-subscription-change.md
  _posts/2018-11-25-subscription-types.md
  _posts/2018-11-25-time-to-finish.md
  _posts/2018-11-25-typing-in-japanese.md
  _posts/2018-11-25-unlock-new-lessons.md
  _posts/2018-11-25-user-synonyms.md
  _posts/2018-11-25-wanikani-content.md
  _sass/tutorials.scss
  _sass/typography.scss
  _sass/wanikani/banner.scss
  _sass/wanikani/overrides.scss
  _sets/getting-started.md
  css/screen.scss
  index.html
Labels: enhancement, ship it 🐿️

#7 Version lock Ruby to 2.3.6
  Gemfile
  Gemfile.lock
Labels: enhancement, ship it 🐿️

#8 Posts — Design Fixes 20181212
  _config.yml
  _includes/listings.html
  _layouts/post.html
  _sass/variables.scss
  _sass/wanikani/banner.scss
  _sass/wanikani/nav.scss
  _sass/wanikani/overrides.scss
  index.html
  siteicon.png
Labels: enhancement, ship it 🐿️

#9 Add password protection to Netlify PR deploys
  .github/pull_request_template.md
  netlify.toml
  netlify_headers
Labels: enhancement

#10 Posts design fixes 20181217
  _data/navigation.yml
  _sass/tutorials.scss
  _sass/wanikani/overrides.scss
  faq.html
Labels: enhancement

#11 Fix category links on landing page
  index.html
Labels: bug

#19 Update SRS Stage document with fixed example, more details, and using updated term
  _posts/2018-11-25-reset-level.md
  _posts/2018-11-25-srs-stages.md
Labels: bug, ship it 🐿️

#21 Fix/srs remove outdated links
  _posts/2018-11-25-srs.md
Labels: ship it 🐿️

#22 Fix/unlocking kanji broken link
  _posts/2018-10-31-unlocking-kanji.md
Labels: ship it 🐿️

#16 Fix typo — per year, not per month
  _posts/2018-11-25-subscription-plans.md
Labels: bug
